import assert from 'node:assert/strict';
const base='http://localhost:4000/api';let jar='';async function req(path,body,expected=200,method='POST'){const res=await fetch(base+path,{method,headers:{'Content-Type':'application/json','X-Requested-With':'e-kharid',Cookie:jar},body:body?JSON.stringify(body):undefined});const cookies=res.headers.getSetCookie();if(cookies.length)jar=cookies.map(c=>c.split(';')[0]).join('; ');const data=await res.json();assert.equal(res.status,expected,JSON.stringify(data));return data;}
const stamp=String(Date.now()).slice(-8);const registration={name:'Synthetic Test Farmer',email:`test-${stamp}@example.test`,mobile:`98${stamp}`,password:'Synthetic-Only-Password!21',aadhaar:'999988887777',pan:'ABCDE1234F',dob:'1990-01-01',gender:'Male',address:'Demo village road',village:'Demo Village',district:'Sitapur',state:'Uttar Pradesh',pin:'226001',land:'TEST-100',crop:'Wheat',quantity:5,consent:true};
const c=await req('/auth/register',registration);assert.ok(c.demoCode);await req('/auth/verify-otp',{challengeId:c.challengeId,code:'000000'},400);await req('/auth/verify-otp',{challengeId:c.challengeId,code:c.demoCode});const profile=await req('/farmer/profile',null,200,'GET');assert.equal(profile.aadhaar,'XXXX XXXX 7777');assert.ok(!('aadhaarEncrypted' in profile));assert.ok(!('passwordHash' in profile));
const form=new FormData();form.append('type','PAN Document');form.append('file',new Blob(['%PDF-1.4\nDemo synthetic document'],{type:'application/pdf'}),'test.pdf');const upload=await fetch(`${base}/documents`,{method:'POST',headers:{Cookie:jar,'X-Requested-With':'e-kharid'},body:form});assert.equal(upload.status,201);const docs=await req('/documents',null,200,'GET');const document=docs.at(-1);const raw=await fetch(`${base}/documents/${document._id}`,{headers:{Cookie:jar}});assert.equal(await raw.text(),'%PDF-1.4\nDemo synthetic document');
const config=await fetch(`${base}/config`).then(r=>r.json());const district=config.demoAccounts.find(a=>a.role==='district');await req('/auth/login',{login:district.email,password:district.password,role:'district'});await req(`/documents/${document._id}`,null,404,'GET');
const farmer=config.demoAccounts.find(a=>a.role==='farmer');await req('/auth/login',{login:farmer.email,password:farmer.password,role:'farmer'});await req(`/documents/${document._id}`,null,404,'GET');
const forbidden=await fetch(`${base}/farmer/profile`,{method:'PUT',headers:{Cookie:jar,'Content-Type':'application/json'},body:JSON.stringify({name:'Malicious',address:'x',village:'x'})});assert.equal(forbidden.status,403);
const bad=new FormData();bad.append('type','PAN Document');bad.append('file',new Blob(['not a PDF'],{type:'application/pdf'}),'fake.pdf');const rejected=await fetch(`${base}/documents`,{method:'POST',headers:{Cookie:jar,'X-Requested-With':'e-kharid'},body:bad});assert.equal(rejected.status,400);
console.log('PASS: OTP registration, invalid OTP rejection, masked identity, authenticated encrypted document round-trip, cross-district/farmer denial, request verification, file signature validation.');
